### ISSUE TITLE
Can't run script

### ISSUE THREAD

**Issue by jifop** [llvllch/dolphin#1]
Error:

Can't run script without errors even though module is installed.

sudo python3 palomino.py
Traceback (most recent call last):
  File "palomino.py", line 5, in <module>
    from IT8951 import constants
ModuleNotFoundError: No module named 'IT8951'

pip3 list
Package             Version
------------------- ---------
IT8951              0.1.1

**Comment by veebch** [comment]
My guess is that it isnt installed as root.... see if it's still listed when you try sudo pip3 list

**Comment by jifop** [comment]
Thankyou, that solved that.

Now I need to work on this one: 

  File "palomino.py", line 225, in <module>
    display = AutoEPDDisplay(vcom=config['display']['vcom'], rotate=args.rotate, spi_hz=60000000)
  File "/home/volumio/.local/lib/python3.7/site-packages/IT8951/display.py", line 224, in __init__
    epd = EPD(vcom=vcom, bus=bus, device=device, data_hz=spi_hz)
  File "/home/volumio/.local/lib/python3.7/site-packages/IT8951/interface.py", line 33, in __init__
    self.update_system_info()
  File "/home/volumio/.local/lib/python3.7/site-packages/IT8951/interface.py", line 103, in update_system_info
    raise RuntimeError("communication with device failed")
RuntimeError: communication with device failed

Although this is less suprising as I'm running it on the volumio Pi so need to work out if SPI is working

**Comment by veebch** [comment]
`sudo raspi-config nonint do spi 0` :)
